#Tomcat Server
server: 
  port: 8080


spring:
#Security
  security:
    user:
      name: admin
      password: 1234
#Database
  datasource:
    url: jdbc:mysql://localhost:3306/manageMy$db
    username: root
    password: rootpass
 
  